global.Inventory_Spell = array_create(INVENTORY_SLOTS_SPELLS_USED,false);
global.Inventory_Treasure = array_create(INVENTORY_SLOTS_TREASURE_USED,false);

if global.DebugMode = true
{
	global.Inventory_Treasure[0] = true
	global.Inventory_Treasure[1] = true
	global.Inventory_Treasure[2] = true
	global.Inventory_Treasure[3] = true
	global.Inventory_Treasure[4] = true
	global.Inventory_Treasure[5] = true
	global.Inventory_Treasure[6] = true
	global.Inventory_Treasure[7] = true
	global.Inventory_Treasure[8] = true
	global.Inventory_Treasure[9] = true
	global.Inventory_Treasure[10] = true
	global.Inventory_Treasure[11] = true
	global.Inventory_Treasure[12] = true
	global.Inventory_Treasure[13] = true
	global.Inventory_Treasure[14] = true
	global.Inventory_Treasure[15] = true
	global.Inventory_Treasure[16] = true
	global.Inventory_Treasure[17] = true
	global.Inventory_Treasure[18] = true
	global.Inventory_Treasure[19] = true
	global.Inventory_Treasure[20] = true
	global.Inventory_Treasure[21] = true
	global.Inventory_Treasure[22] = true
	global.Inventory_Treasure[23] = true
	global.Inventory_Treasure[24] = true
	global.Inventory_Treasure[25] = true
	global.Inventory_Treasure[26] = true
	global.Inventory_Treasure[27] = true
	global.Inventory_Treasure[28] = true
	global.Inventory_Treasure[29] = true
	global.Inventory_Treasure[30] = true
	global.Inventory_Treasure[31] = true
	global.Inventory_Treasure[32] = true
	global.Inventory_Treasure[33] = true
	global.Inventory_Treasure[34] = true
	global.Inventory_Treasure[35] = true
	global.Inventory_Treasure[36] = true
	global.Inventory_Treasure[37] = true
	global.Inventory_Treasure[38] = true
	global.Inventory_Treasure[39] = true
}
