function Audio_Init_Soundtrack()
{
	global.MusicTracks = 
	{
		//The variables of each audio track, most of it is set to Silence by default because I still need to edit them
		Silence : {Asset : Music_Silence, IntroLength : 0.25, LoopLength : 0.25},
		Beach_Ocean : {Asset : Music_Beach_Ocean, IntroLength : 1.751, LoopLength : 19.845},
		Blacksmith : {Asset : Music_Blacksmith, IntroLength : 2.906, LoopLength : 18.811},
		Canyon_Normal : {Asset : Music_Canyon_Normal, IntroLength : 2.262, LoopLength : 19.471},
		Canyon_Cave : {Asset : Music_Canyon_Cave, IntroLength : 1.800, LoopLength : 19.537},
		Desert : {Asset : Music_Desert, IntroLength : 2.037, LoopLength : 19.666},
		Desert_Ocean : {Asset : Music_Desert_Ocean, IntroLength : 1.967, LoopLength : 19.783},
		Fairy_Canyon : {Asset : Music_Fairy_Canyon, IntroLength : 1.756, LoopLength : 18.228},
		Fairy_Organ : {Asset : Music_Fairy_Organ, IntroLength : 1.842, LoopLength : 18.228},
		Fairy_Desert : {Asset : Music_Fairy_Desert, IntroLength : 1.754, LoopLength : 18.228},
		Fireplace_Normal : {Asset : Music_Fireplace_Normal, IntroLength : 1.811, LoopLength : 19.927},
		Fireplace_Southport : {Asset : Music_Fireplace_Southport, IntroLength : 1.779, LoopLength : 19.497},
		Forest : {Asset : Music_Forest, IntroLength : 1.429, LoopLength : 19.996},
		Forest_Ocean : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Forest_Stream : {Asset : Music_Forest_Stream, IntroLength : 2.082, LoopLength : 19.478},
		Inn : {Asset : Music_Inn, IntroLength : 2.333, LoopLength : 18.461},
		Lava_Stream : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Lava_Wind : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Marsh : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Marsh_Ocean : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Ocean : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Plain : {Asset : Music_Plain, IntroLength : 1.755, LoopLength : 19.797},
		Plain_Stream : {Asset : Music_Plain_Stream, IntroLength : 1.764, LoopLength : 19.989},
		Sirram : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Twinkle_Normal : {Asset : Music_Twinkle_Normal, IntroLength : 1.774, LoopLength : 20.053},
		Twinkle_Dad : {Asset : Music_Twinkle_Dad, IntroLength : 2.593, LoopLength : 20.056},
		Shrine_Earth_Ambient : {Asset : Music_Shrine_Earth_Ambient, IntroLength : 2.232, LoopLength : 39.467},
		Shrine_Earth_Boss : {Asset : Music_Shrine_Earth_Boss, IntroLength : 1.751, LoopLength : 19.992},
		Shrine_Earth_Regular : {Asset : Music_Shrine_Earth_Regular, IntroLength : 1.751, LoopLength : 332.011},
		Shrine_Earth_Sign : {Asset : Music_Shrine_Earth_Sign, IntroLength : 1.751, LoopLength : 19.705},
		Shrine_Illusion : {Asset : Music_Shrine_Illusion_Regular, IntroLength : 2.041, LoopLength : 59.904},
		Shrine_Illusion_Boss : {Asset : Music_Shrine_Illusion_Boss, IntroLength : 2.086, LoopLength : 17.935},
		Shrine_Illusion_Sign : {Asset : Music_Shrine_Illusion_Sign, IntroLength : 5.684, LoopLength : 17.935},
		Shrine_Air : {Asset : Music_Shrine_Air_Regular, IntroLength : 2.861, LoopLength : 109.002},
		Shrine_Air_Boss : {Asset : Music_Shrine_Air_Boss, IntroLength : 1.805, LoopLength : 20.950},
		Shrine_Air_Sign : {Asset : Music_Shrine_Air_Sign, IntroLength : 5.684, LoopLength : 19.595},
		Shrine_Destiny : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Shrine_Destiny_Boss : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Shrine_Destiny_Sign : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Shrine_Water : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Shrine_Water_Boss : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Shrine_Water_Sign : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Shrine_Strength : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Shrine_Strength_Boss : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Shrine_Strength_Sign : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Shrine_Fire : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Shrine_Fire_Boss : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Shrine_Fire_Sign : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Gauntlet_Llort : {Asset : Music_Shrine_Earth_Boss, IntroLength : 1.751, LoopLength : 19.992},
		Gauntlet_Pasquinade : {Asset : Music_Shrine_Illusion_Boss, IntroLength : 2.086, LoopLength : 17.935},
		Gauntlet_Avianna : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Gauntlet_Malmort : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Gauntlet_Agwanda : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Gauntlet_Warbane : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
		Gauntlet_Ganon : {Asset : Music_Silence, IntroLength : 0, LoopLength : 0},
	}	
}